import Header from "@/components/header";
import { Theme } from "@radix-ui/themes";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body className="bg-white">
        <Theme>
          <div className="h-20">
            <Header />
          </div>

          {children}
        </Theme>
      </body>
    </html>
  );
}
